"""
SearchAgent - backend/app/agents/search_agent.py
-------------------------------------------------
Dynamic Evidence Retrieval Agent.

Responsibilities:
1. Pull requested document evidence (Invoice, PO, GRN, Bank Statement, Line Items) from SQLite
   based on the RetrievalPlan generated by IntentRouterAgent (TASKS 2, 3, 4).
2. Build a comprehensive "evidence_table" containing document metadata and exact line items.
3. Run ChromaDB vector similarity lookup for fuzzy vendor name matches.
"""

import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from sqlalchemy.orm import Session

from app.agents.state import BundleState
from app.core.logging import logger
from app.db.session import SessionLocal
from app.models.models import (
    AuditBundle, BankStatement, BankTransaction, Document,
    GRN, GRNLineItem, Invoice, InvoiceLineItem, PurchaseOrder, POLineItem, Vendor,
)

_CHROMA_DIR = str(
    Path(__file__).resolve().parent.parent.parent / "storage" / "chroma_db"
)
_COLLECTION_NAME = "audit_documents"

_chroma_client = None
_chroma_collection = None
_embedding_fn = None


def _get_chroma():
    """Lazy initialise ChromaDB client and collection."""
    global _chroma_client, _chroma_collection, _embedding_fn

    if _chroma_collection is not None:
        return _chroma_collection

    try:
        import chromadb
        from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

        Path(_CHROMA_DIR).mkdir(parents=True, exist_ok=True)
        _chroma_client = chromadb.PersistentClient(path=_CHROMA_DIR)
        _embedding_fn = SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2"
        )
        _chroma_collection = _chroma_client.get_or_create_collection(
            name=_COLLECTION_NAME,
            embedding_function=_embedding_fn,
            metadata={"hnsw:space": "cosine"},
        )
        logger.info(f"[SearchAgent] ChromaDB initialised at {_CHROMA_DIR}")
    except Exception as exc:
        logger.error(f"[SearchAgent] ChromaDB init failed: {exc}")
        _chroma_collection = None

    return _chroma_collection


DOC_TYPE_MAPPING = {
    "invoice": "invoice",
    "invoices": "invoice",
    "purchase_order": "purchase_order",
    "purchase_orders": "purchase_order",
    "po": "purchase_order",
    "pos": "purchase_order",
    "grn": "grn",
    "grns": "grn",
    "goods_received_note": "grn",
    "goods_received_notes": "grn",
    "bank_statement": "bank_statement",
    "bank_statements": "bank_statement",
    "bank": "bank_statement",
    "bank_transaction": "bank_statement",
    "bank_transactions": "bank_statement",
}

LINE_ITEM_FIELD_NAMES = {
    "description", "qty", "qty_received", "qty_ordered",
    "unit_price", "line_total", "item_code", "line_items"
}


def _filter_document_fields(
    raw_header: Dict[str, Any],
    raw_line_items: List[Dict[str, Any]],
    required_fields: Any
) -> Optional[Dict[str, Any]]:
    """Filter document header and line item fields according to required_fields. Preserves complete evidence by default."""
    is_all = True
    if required_fields and isinstance(required_fields, list) and len(required_fields) > 0:
        if not any(str(f).lower() == "all" for f in required_fields):
            is_all = False

    if is_all:
        doc = dict(raw_header)
        if raw_line_items and "line_items" not in doc:
            doc["line_items"] = raw_line_items
        return doc

    req_set = {str(f).lower().strip() for f in required_fields if f}

    # Determine which fields are header fields vs line item fields
    header_fields = {k: v for k, v in raw_header.items() if k.lower() in req_set}

    # Check if any requested fields are line-item fields
    line_item_field_names = {"description", "qty", "qty_received", "qty_ordered",
                             "unit_price", "line_total", "item_code", "line_items", "items"}
    wants_line_items = bool(req_set & line_item_field_names)

    result_doc = dict(header_fields)

    if wants_line_items and raw_line_items:
        filtered_items = []
        keep_all_item_keys = bool(req_set & {"line_items", "items", "all"})
        for item in raw_line_items:
            if keep_all_item_keys:
                filtered_items.append(dict(item))
            else:
                filtered_item = {k: v for k, v in item.items() if k.lower() in req_set or k.lower() in ("description", "item_code")}
                if filtered_item:
                    filtered_items.append(filtered_item)
        if filtered_items:
            result_doc["line_items"] = filtered_items

    return result_doc if result_doc else dict(raw_header)


def _fetch_bundle_evidence(db: Session, bundle_id: str, plan: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Dynamically retrieve requested documents and line items for the bundle based on RetrievalPlan."""
    raw_req_docs = plan.get("required_documents") if plan else None
    required_fields = plan.get("required_fields", "all") if plan else "all"

    # Respect RetrievalPlan required_documents
    if not raw_req_docs:
        req_docs = {"invoice", "purchase_order", "grn", "bank_statement"}
    elif isinstance(raw_req_docs, list):
        req_docs = set()
        for d in raw_req_docs:
            if isinstance(d, str):
                key = d.lower().strip()
                mapped = DOC_TYPE_MAPPING.get(key, key)
                req_docs.add(mapped)
    elif isinstance(raw_req_docs, str):
        key = raw_req_docs.lower().strip()
        req_docs = {DOC_TYPE_MAPPING.get(key, key)}
    else:
        req_docs = {"invoice", "purchase_order", "grn", "bank_statement"}

    evidence = {
        "bundle_id": bundle_id,
        "vendor_name": None,
        "invoice": None,
        "purchase_order": None,
        "grn": None,
        "bank_statement": None,
    }

    # Fetch Invoice vendor name if Invoice exists
    inv = db.query(Invoice).filter(Invoice.bundle_id == bundle_id).first()
    vname = None
    if inv:
        if inv.vendor_id:
            v = db.query(Vendor).filter(Vendor.vendor_id == inv.vendor_id).first()
            vname = v.name_normalized if v else None
            evidence["vendor_name"] = vname

    # 1. Fetch Invoice if requested
    if "invoice" in req_docs and inv:
        po_for_inv = db.query(PurchaseOrder).filter(PurchaseOrder.bundle_id == bundle_id).first()
        po_ref = po_for_inv.po_number if po_for_inv else (inv.po_ref_raw if inv.po_ref_raw else None)

        inv_lines = db.query(InvoiceLineItem).filter(InvoiceLineItem.invoice_id == inv.invoice_id).all()
        raw_line_items = [
            {
                "description": l.description,
                "qty": float(l.qty) if l.qty is not None else None,
                "unit_price": float(l.unit_price) if l.unit_price is not None else None,
                "line_total": float(l.line_total) if l.line_total is not None else None,
            }
            for l in inv_lines
        ]
        raw_header = {
            "invoice_number": inv.invoice_number,
            "invoice_date": str(inv.invoice_date) if inv.invoice_date else None,
            "due_date": str(inv.due_date) if inv.due_date else None,
            "total_amount": float(inv.total_amount) if inv.total_amount is not None else None,
            "subtotal": float(inv.subtotal) if inv.subtotal is not None else None,
            "tax_amount": float(inv.tax_amount) if inv.tax_amount is not None else None,
            "vendor_name": vname,
            "purchase_order": po_ref,
            "po_number": po_ref,
        }
        evidence["invoice"] = _filter_document_fields(raw_header, raw_line_items, required_fields)

    # 2. Fetch Purchase Order if requested
    if "purchase_order" in req_docs:
        po = db.query(PurchaseOrder).filter(PurchaseOrder.bundle_id == bundle_id).first()
        if po:
            po_lines = db.query(POLineItem).filter(POLineItem.po_id == po.po_id).all()
            raw_line_items = [
                {
                    "item_code": l.item_code,
                    "description": l.description,
                    "qty": float(l.qty) if l.qty is not None else None,
                    "unit_price": float(l.unit_price) if l.unit_price is not None else None,
                    "line_total": float(l.line_total) if l.line_total is not None else None,
                }
                for l in po_lines
            ]
            raw_header = {
                "po_number": po.po_number,
                "po_date": str(po.po_date) if po.po_date else None,
                "total_amount": float(po.total_amount) if po.total_amount is not None else None,
                "subtotal": float(po.subtotal) if po.subtotal is not None else None,
                "tax_amount": float(po.tax_amount) if po.tax_amount is not None else None,
            }
            evidence["purchase_order"] = _filter_document_fields(raw_header, raw_line_items, required_fields)

    # 3. Fetch GRN (Goods Received Note) if requested
    if "grn" in req_docs:
        grn = db.query(GRN).filter(GRN.bundle_id == bundle_id).first()
        if grn:
            grn_lines = db.query(GRNLineItem).filter(GRNLineItem.grn_id == grn.grn_id).all()
            raw_line_items = [
                {
                    "description": l.description,
                    "qty_ordered": float(l.qty_ordered) if l.qty_ordered is not None else None,
                    "qty_received": float(l.qty_received) if l.qty_received is not None else None,
                    "unit_price": float(l.unit_price) if l.unit_price is not None else None,
                    "line_total": float(l.line_total) if l.line_total is not None else None,
                }
                for l in grn_lines
            ]
            raw_header = {
                "grn_number": grn.grn_number,
                "grn_date": str(grn.grn_date) if grn.grn_date else None,
                "delivery_note_number": grn.delivery_note_number,
                "received_condition": grn.received_condition,
            }
            evidence["grn"] = _filter_document_fields(raw_header, raw_line_items, required_fields)

    # 4. Fetch Bank Statement if requested
    if "bank_statement" in req_docs:
        stmt = db.query(BankStatement).filter(BankStatement.bundle_id == bundle_id).first()
        if stmt:
            stmt_txns = db.query(BankTransaction).filter(BankTransaction.statement_id == stmt.statement_id).all()
            raw_txns = [
                {
                    "txn_date": str(t.txn_date) if t.txn_date else None,
                    "description": t.description_raw,
                    "debit": float(t.debit_amount) if t.debit_amount is not None else 0.0,
                    "credit": float(t.credit_amount) if t.credit_amount is not None else 0.0,
                    "running_balance": float(t.running_balance) if t.running_balance is not None else None,
                    "extracted_ref": t.extracted_ref,
                    "extracted_invoice_number": t.extracted_invoice_number,
                }
                for t in stmt_txns
            ]
            raw_header = {
                "account_number": stmt.account_number,
                "statement_date": str(stmt.statement_date) if stmt.statement_date else None,
                "period_start": str(stmt.period_start) if stmt.period_start else None,
                "period_end": str(stmt.period_end) if stmt.period_end else None,
                "opening_balance": float(stmt.opening_balance) if stmt.opening_balance is not None else None,
                "closing_balance": float(stmt.closing_balance) if stmt.closing_balance is not None else None,
                "transactions": raw_txns,
            }
            inv_num = inv.invoice_number if inv else ""
            if inv_num and any(inv_num.lower() in (t.get("extracted_invoice_number") or "").lower() or inv_num.lower() in (t.get("description") or "").lower() for t in raw_txns):
                raw_header["payment_status"] = "confirmed"
            else:
                raw_header["payment_status"] = "unconfirmed" if inv else "available"
            
            evidence["bank_statement"] = _filter_document_fields(raw_header, raw_txns, required_fields)
        else:
            inv_num = inv.invoice_number if inv else ""
            bt = None
            if inv_num:
                bt = db.query(BankTransaction).filter(
                    BankTransaction.extracted_invoice_number.ilike(f"%{inv_num}%")
                ).first()
                if not bt:
                    bt = db.query(BankTransaction).filter(
                        BankTransaction.description_raw.ilike(f"%{inv_num}%")
                    ).first()

            if bt:
                raw_header = {
                    "payment_status": "confirmed",
                    "payment_date": str(bt.txn_date) if bt.txn_date else None,
                    "payment_amount": float(bt.debit_amount or bt.credit_amount or 0),
                    "bank_reference": bt.extracted_ref or "",
                    "description": bt.description_raw or "",
                    "transactions": [{
                        "txn_date": str(bt.txn_date) if bt.txn_date else None,
                        "description": bt.description_raw,
                        "debit": float(bt.debit_amount) if bt.debit_amount is not None else 0.0,
                        "credit": float(bt.credit_amount) if bt.credit_amount is not None else 0.0,
                        "extracted_ref": bt.extracted_ref,
                    }]
                }
                evidence["bank_statement"] = _filter_document_fields(raw_header, raw_header["transactions"], required_fields)
            else:
                evidence["bank_statement"] = None

    return evidence


def search_node(state: BundleState) -> Dict[str, Any]:
    """LangGraph Node: SearchAgent."""
    bundle_id = state.get("bundle_id")
    plan = state.get("retrieval_plan")
    user_query = state.get("user_query") or ""
    start = time.time()

    if not bundle_id and user_query:
        from app.agents.intent_router_agent import _lookup_bundle_by_query
        bundle_id = _lookup_bundle_by_query(user_query)

    logger.info(f"[SearchAgent] Running dynamic evidence retrieval for bundle {bundle_id}")

    if not bundle_id:
        logger.warning("[SearchAgent] No bundle_id resolved for search node. Returning empty evidence table.")
        empty_evidence = {
            "bundle_id": None,
            "vendor_name": None,
            "invoice": None,
            "purchase_order": None,
            "grn": None,
            "bank_statement": None,
        }
        return {"bundle_id": None, "evidence_table": empty_evidence, "vendor_similarity_matches": []}

    db = SessionLocal()
    try:
        evidence_table = _fetch_bundle_evidence(db, bundle_id, plan)

        # Vector similarity search in ChromaDB
        vendor_matches = []
        vendor_name = evidence_table.get("vendor_name")
        if vendor_name:
            collection = _get_chroma()
            if collection:
                try:
                    # Upsert vendor embedding for current bundle
                    collection.upsert(
                        documents=[vendor_name],
                        ids=[bundle_id],
                        metadatas=[{"bundle_id": bundle_id, "vendor_name": vendor_name}],
                    )
                    # Query similarity matches
                    results = collection.query(
                        query_texts=[vendor_name],
                        n_results=4,
                    )
                    if results and results.get("metadatas"):
                        vendor_matches = [
                            m for m in results["metadatas"][0] if m.get("bundle_id") != bundle_id
                        ]
                except Exception as exc:
                    logger.warning(f"[SearchAgent] ChromaDB query error: {exc}")

        latency = int((time.time() - start) * 1000)
        logger.info(f"[SearchAgent] Dynamic evidence retrieval complete in {latency}ms")

        return {
            "evidence_table": evidence_table,
            "vendor_similarity_matches": vendor_matches,
        }
    finally:
        db.close()


DOC_TYPE_LABELS = {
    "invoice": "Invoice",
    "purchase_order": "Purchase Order",
    "grn": "GRN",
    "bank_statement": "Bank Statement"
}


def _fetch_bundle_source_documents(
    db: Session,
    bundle_id: str,
    required_documents: Optional[List[str]] = None
) -> List[Dict[str, Any]]:
    """
    Retrieve validated physical source documents strictly belonging to bundle_id.
    Filters by required_documents if provided.
    """
    if not bundle_id:
        return []

    req_set = None
    if required_documents and isinstance(required_documents, list) and len(required_documents) > 0:
        req_set = {DOC_TYPE_MAPPING.get(d.lower().strip(), d.lower().strip()) for d in required_documents if isinstance(d, str)}

    docs = db.query(Document).filter(Document.bundle_id == bundle_id).all()
    source_docs = []

    for d in docs:
        dtype = DOC_TYPE_MAPPING.get(d.doc_type.lower().strip(), d.doc_type)
        if req_set and dtype not in req_set:
            continue

        fname = Path(d.file_path).name if d.file_path else f"{dtype}.pdf"
        label = DOC_TYPE_LABELS.get(dtype, dtype.replace("_", " ").title())

        # Check for exact document number to make label specific
        if dtype == "invoice":
            inv = db.query(Invoice).filter(Invoice.bundle_id == bundle_id).first()
            if inv and inv.invoice_number:
                label = f"Invoice {inv.invoice_number}"
        elif dtype == "purchase_order":
            po = db.query(PurchaseOrder).filter(PurchaseOrder.bundle_id == bundle_id).first()
            if po and po.po_number:
                label = f"PO {po.po_number}"
        elif dtype == "grn":
            grn = db.query(GRN).filter(GRN.bundle_id == bundle_id).first()
            if grn and grn.grn_number:
                label = f"GRN {grn.grn_number}"
        elif dtype == "bank_statement":
            bs = db.query(BankStatement).filter(BankStatement.bundle_id == bundle_id).first()
            if bs and bs.account_number:
                label = f"Bank Statement ({bs.account_number})"

        source_docs.append({
            "document_id": str(d.document_id),
            "doc_type": dtype,
            "filename": fname,
            "label": label,
            "url": f"/api/v1/bundles/{bundle_id}/files/{fname}",
            "bundle_id": str(bundle_id),
        })

    order = {"invoice": 1, "purchase_order": 2, "grn": 3, "bank_statement": 4}
    source_docs.sort(key=lambda x: (order.get(x["doc_type"], 99), x["filename"]))
    return source_docs

